# SPDX-FileCopyrightText: 2020 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: REUSE Compliance Check

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: REUSE version
      uses: ./
      with:
        args: --version
    - name: REUSE lint
      uses: ./
      with:
        args: --include-submodules lint
    - name: REUSE SPDX SBOM
      uses: ./
      with:
        args: spdx
